title: Demonstratif Portfolio
theme: jekyll-theme-modernist
description: The Portfolio of Hugo Jacques. Mainly for a Online Portfolio Assignment

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
